# Generated by Django 5.0.12 on 2025-03-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dt", models.DateTimeField()),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("wind_speed", models.FloatField(blank=True, null=True)),
                ("temp_air", models.FloatField(blank=True, null=True)),
                ("ghi", models.FloatField(blank=True, null=True)),
                ("dni", models.FloatField(blank=True, null=True)),
                ("dhi", models.FloatField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("dt", "lat", "lon")},
            },
        ),
    ]
