# Generated by Django 5.0.12 on 2025-03-07 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coordsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="weatherdata",
            unique_together=set(),
        ),
    ]
