#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo COLLECTSTATIC
python /app/manage.py collectstatic --noinput --settings config.settings.production

echo MIGRATE
python /src/manage.py showmigrations --settings config.settings.production
python /src/manage.py migrate --settings config.settings.production

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
