#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo COLLECTSTATIC
python /app/manage.py collectstatic --noinput

echo MIGRATE
python /src/manage.py showmigrations
python /src/manage.py migrate

exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app
